# Generated by Django 3.0.7 on 2020-06-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='scheme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Schemes'),
            preserve_default=False,
        ),
    ]
