# Generated by Django 3.0.7 on 2020-06-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_schemes_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemes',
            name='supervisor',
        ),
    ]
