# Generated by Django 3.0.7 on 2020-06-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='scheme_number',
            new_name='farm_number',
        ),
    ]
